[phases.setup]
nixPkgs = ["nodejs-18_x"]

[phases.install]
cmds = ["npm ci"]

[phases.build]
cmds = ["DISABLE_ESLINT_PLUGIN=true npm run build"]

[start]
cmd = "npm run start:prod"

[variables]
CI = "false"
DISABLE_ESLINT_PLUGIN = "true"
TSC_COMPILE_ON_ERROR = "true"
